### ISSUE TITLE
Loading repositories

### ISSUE THREAD

**Issue by kirschkematthias** [cfillion/reapack#86] opened 2024-09-04 10:56 UTC
since short time I have problems to download any script for Reaper. 
I'm running MacOs 15 on an M3 MacBook Pro with the newest version of Reaper, SWS and Reapack. Also some scripts I have downloaded before are not showing up anymore, they are running but nothing happens, no gui etc. 

many greetings

Matthias

following errors appear:

https://reapack.com/index.xml:
  HTTP response code said error (22): The requested URL returned error: 405

https://github.com/ReaTeam/ReaScripts/raw/master/index.xml:
  HTTP response code said error (22): The requested URL returned error: 405

https://github.com/ReaTeam/Themes/raw/master/index.xml:
  HTTP response code said error (22): The requested URL returned error: 405

https://raw.githubusercontent.com/ReaTeam/Extensions/master/index.xml:
  HTTP response code said error (22): The requested URL returned error: 405

https://bitbucket.org/kawaCat/reascript-m2bpack/raw/master/index.xml:
  HTTP response code said error (22): The requested URL returned error: 405

https://github.com/GoranKovac/ReaScripts/raw/master/index.xml:
  HTTP response code said error (22): The requested URL returned error: 405

https://github.com/Audiokinetic/Reaper-Tools/raw/main/index.xml:
  HTTP response code said error (22): The requested URL returned error: 405

https://github.com/Neutronic/ReaScripts/raw/master/index.xml:
  HTTP response code said error (22): The requested URL returned error: 405

https://github.com/RobU23/ReaScripts/raw/master/index.xml:
  HTTP response code said error (22): The requested URL returned error: 405

https://nvk.tools/index.xml:
  HTTP response code said error (22): The requested URL returned error: 405

https://github.com/IXix/JSFX/raw/master/index.xml:
  HTTP response code said error (22): The requested URL returned error: 405

https://raw.githubusercontent.com/TukanStudios/TUKAN_STUDIOS_PLUGINS/main/index2.xml:
  HTTP response code said error (22): The requested URL returned error: 405

https://github.com/jeremybernstein/ReaScripts/raw/main/index.xml:
  HTTP response code said error (22): The requested URL returned error: 405

https://raw.githubusercontent.com/Bird-Bird/ReaScript_Testing/main/index.xml:
  HTTP response code said error (22): The requested URL returned error: 405

https://raw.githubusercontent.com/iliaspoulakis/Reaper-Tools/master/index.xml:
  HTTP response code said error (22): The requested URL returned error: 405

https://github.com/TeamAudio/reascripts/raw/main/index.xml:
  HTTP response code said error (22): The requested URL returned error: 405

https://github.com/Sonic-Anomaly/Sonic-Anomaly-JSFX/raw/master/index.xml:
  HTTP response code said error (22): The requested URL returned error: 405

https://bitbucket.org/kawaCat/kawascript2/raw/master/index.xml:
  HTTP response code said error (22): The requested URL returned error: 405

https://github.com/helgoboss/reaper-packages/raw/master/index.xml:
  HTTP response code said error (22): The requested URL returned error: 405

https://bit.ly/2XnYrQ9:
  HTTP response code said error (22): The requested URL returned error: 405

https://acendan.github.io/reascripts/index.xml:
  HTTP response code said error (22): The requested URL returned error: 405

https://github.com/tormyvancool/TormyVanCool_ReaPack_Scripts/raw/master/index.xml:
  HTTP response code said error (22): The requested URL returned error: 405

https://github.com/X-Raym/REAPER-ReaScripts/raw/master/index.xml:
  HTTP response code said error (22): The requested URL returned error: 405

https://raw.githubusercontent.com/MichaelPilyavskiy/ReaScripts/master/index.xml:
  HTTP response code said error (22): The requested URL returned error: 405

https://github.com/ReaTeam/LangPacks/raw/master/index.xml:
  HTTP response code said error (22): The requested URL returned error: 405

https://github.com/ReaTeam/JSFX/raw/master/index.xml:
  HTTP response code said error (22): The requested URL returned error: 405

**Comment by cfillion** [comment] 2024-09-04 12:10
405 is the HTTP error code for "Method Not Allowed". All of the URLs listed above properly responds to GET (<-- the method) requests as sent by ReaPack. This suggests there is something sitting between ReaPack/REAPER and the web blocking the connection and emitting that error.

A firewall or proxy server on your computer/network, maybe?

> Also some scripts I have downloaded before are not showing up anymore, they are running but nothing happens, no gui etc.

This sounds like a separate problem. Can you list the scripts in question?

**Comment by kirschkematthias** [comment] 2024-09-04 12:32
When I go to Manage Repositories under Network settings I found This Address: https://bit.ly/2XnYrQ9
I don't know if this is right.


The other Problem I got with rodilab_color palette
When I run it, nothing happens, just under action menu I see that it is running.:
<img width="486" alt="SCR-20240904-mwsf" src="https://github.com/user-attachments/assets/986d4aa3-6f59-4402-b5f3-f9fe5b6ccff6">

many greetings Matthmany greetings

Matthias

**Comment by cfillion** [comment] 2024-09-04 12:46
> When I go to Manage Repositories under Network settings I found This Address: https://bit.ly/2XnYrQ9
I don't know if this is right.

It's the cause of the 405 errors. A repository URL should not be in the proxy server field. The field should be empty. 

> The other Problem I got with rodilab_color palette
When I run it, nothing happens, just under action menu I see that it is running.:

This seems to be an issue with macOS 15 beta breaking ReaImGui graphics. Try selecting OpenGL instead of Metal as the renderer in Preferences > Plug-ins > ReaImGui.

**Comment by kirschkematthias** [comment] 2024-09-04 13:22
Ok. After killing the url the errors disapeared, Now the only problem is to load the repository from Sexon:
https://github.com/GoranKovac/ReaScripts/raw/master/index.xml
On my old i7 Mac I don't have problems with the url.

Thank you for your quick answer.

many greetings Matthmany greetings

Matthias

**Comment by cfillion** [comment] 2024-09-04 13:29
> Ok. After killing the url the errors disapeared, Now the only problem is to load the repository from Sexon:
https://github.com/GoranKovac/ReaScripts/raw/master/index.xml

What is the new error message? The URL itself is correct.

**Comment by kirschkematthias** [comment] 2024-09-04 14:01
There is no error message, it seems to load, but very quick the window closes, and the scripts are not there.
Looking in the actions list there are only three action from sexan, and I can't find the Paranormal FX Router:

<img width="987" alt="SCR-20240904-obyq" src="https://github.com/user-attachments/assets/76134247-2592-4268-82f1-2b73c3ce266c">

on my old computer it looks like this:

<img width="517" alt="SCR-20240904-obat" src="https://github.com/user-attachments/assets/e76873c5-9093-40f0-bca7-2ce44e46e4ba">

many greetings

Matthias

**Comment by cfillion** [comment] 2024-09-04 14:09
> Looking in the actions list there are only three action from sexan, and I can't find the Paranormal FX Router:

You can install the remaining ones from ReaPack > Browse packages. You might have the auto-install option enabled on the other computer.

> There is no error message, it seems to load, but very quick the window closes

This is likely the same issue with macOS 15 and ReaImGui as rodilab's Color palette above

**Comment by kirschkematthias** [comment] 2024-09-04 15:24
The packes will not install, sorry.
Just the three
.......
Now I get Installed some of the packeges and I got the same GUI problem.

Thanks a lot for your help.


many greetings

Matthias

**Comment by cfillion** [comment] 2024-09-04 16:07
(Closing this since the original question is solved and the remaining GUI problem is not related to ReaPack. Hopefully Apple will fix whatever they broke in macOS 15 before its final release. In case, I'll setup a macOS 15 VM to debug this in the next few weeks...)

**Closed by cfillion** 2024-09-04 16:07 UTC

**Comment by cfillion** [comment] 2024-09-19 06:14
I've just released ReaImGui v0.9.3 with a fix for issue with macOS 15 "Sequoia". Run *ReaPack > Synchronize packages* and restart REAPER to get the update.

**Comment by kirschkematthias** [comment] 2024-09-19 08:10
Thank you so much. No it works perfect!!!


many greetings

Matthias



A garden is finished when there is nothing left to remove.


Matthias Kirschke

Potsdamer Str. 100
10785 Berlin
Germany

mobil:+49 171 6535862

***@***.***

Am 19.09.2024 um 08:15 schrieb Christian Fillion ***@***.***>:


I've just released ReaImGui v0.9.3 with a fix for issue with macOS 15 "Sequoia". Run ReaPack > Synchronize packages and restart REAPER to get the update.
