### ISSUE TITLE
Package list does not appear 

### ISSUE THREAD

**Issue by jmylesmusic** [cfillion/reapack#49] opened 2022-05-28 19:57 UTC
I click "Extensions > ReaPack > Browse packages", but the actual packages list does not appear after clicking.

**Comment by cfillion** [comment] 2022-05-28 20:27
Does it work via the Action List? "ReaPack: Browse packages..."

If not, which OS, how many monitors/in what arrangement, and can you share your reapack.ini?

**Comment by nekoshang** [comment] 2022-07-13 09:18
I was also having this problem on windows. I solved it by:

- closing reaper
- renaming _reapack.ini_ in root of reaper installation directory to _reapack.ini.backup_ 
- restarting reaper
- adding any missing repositories using the usual method (you can see what repositories you had before by opening _reapack.ini.backup_ in a text editor)
- if you get any errors to do with _ssl_ then in the manage repositories menu, there is a network option to disable verification of the authenticity of ssl/tls certificates

Everything is now working again for me. My setup has multiple portable versions of reaper on different devices which are synced using the cloud, so that may have been the cause of the problem, not sure.

**Closed** 2022-10-07 18:48 UTC
